# Generated by Django 3.1.3 on 2020-11-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=300, null=True)),
                ('FirstName', models.CharField(max_length=300, null=True)),
                ('LastName', models.CharField(max_length=300, null=True)),
                ('password', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='userSignup',
        ),
    ]
