# Generated by Django 3.1.3 on 2020-11-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201122_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=300, null=True)),
                ('password', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
