# Generated by Django 3.1.3 on 2020-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201122_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ContactNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='FirstName',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='LastName',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ProfilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
