# Generated by Django 3.1.3 on 2020-11-22 19:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cuisinetype',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Thai', 'Thai'), ('Indonesian', 'Indonesian'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Japanese', 'Japanese'), ('Greece', 'Greece'), ('French', 'French'), ('Moroccan', 'Moroccan')], max_length=78, null=True),
        ),
    ]
