# Generated by Django 3.1.3 on 2020-11-22 19:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_cuisinetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=300, null=True)),
                ('password', models.CharField(max_length=300, null=True)),
                ('OpeningTime', models.TimeField(null=True)),
                ('ClosingTime', models.TimeField(null=True)),
                ('Location', models.TextField(null=True)),
                ('foodtype', models.CharField(choices=[('Veg', ' Veg'), ('NonVeg', 'NonVeg'), ('Both', 'Both')], max_length=300, null=True)),
                ('cuisinetype', multiselectfield.db.fields.MultiSelectField(choices=[('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Thai', 'Thai'), ('Indonesian', 'Indonesian'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Japanese', 'Japanese'), ('Greece', 'Greece'), ('French', 'French'), ('Moroccan', 'Moroccan')], max_length=78, null=True)),
                ('BusinessID', models.CharField(max_length=300, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('ProfilePic', models.ImageField(null=True, upload_to='')),
                ('ContactNo', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
