# Generated by Django 3.1.3 on 2020-11-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='TopFoodItems',
            field=models.TextField(null=True),
        ),
    ]
