# Generated by Django 3.1.3 on 2020-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hotel_topfooditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ProfilePic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Username',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
