# Generated by Django 3.1.3 on 2020-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201124_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='BusinessID',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
