# Generated by Django 3.1.3 on 2020-11-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201124_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ProfilePic',
        ),
    ]
