from django.urls import path
from . import views

urlpatterns = [
    path('', views.login),
    path('login/', views.login),
    path('userSignup/', views.userSignup),
    path('hotelSignup/', views.hotelSignup),
    path('Userprofile/', views.Userprofile),
    path('mainscreen/', views.mainscreen),
    path('updateUserProfile/', views.updateUserProfile),
    path('updateHotelProfile/', views.updateHotelProfile),
    path('hotelpage/', views.hotelpage),
    path('mainscreen/arribamexicangrill/', views.arribamexicangrill),
    path('mainscreen/casinoarizona/', views.casinoarizona),
    path('mainscreen/chopandwok/', views.chopandwok),
    path('mainscreen/defacloitaliangrocery/', views.defacloitaliangrocery),
    path('mainscreen/flosnewasiancuisine/', views.flosnewasiancuisine),
    path('mainscreen/flowerchild/', views.flowerchild),
    path('mainscreen/francositaliancaffe/', views.francositaliancaffe),
    path('mainscreen/freshmint/', views.freshmint),
    path('mainscreen/georgesonsasiancuisine/', views.georgesonsasiancuisine),
    path('mainscreen/guidoschicagomeatdeli/', views.guidoschicagomeatdeli),
    path('mainscreen/habanero/', views.habanero),
    path('mainscreen/indianparadise/', views.indianparadise),
    path('mainscreen/jadepalace/', views.jadepalace),
    path('mainscreen/lasthaicuisine/', views.lasthaicuisine),
    path('mainscreen/loloschickenwaffles/', views.loloschickenwaffles),
    path('mainscreen/losolivosmexicanpatio/', views.losolivosmexicanpatio),
    path('mainscreen/mallesthaibistro/', views.mallesthaibistro),
    path('mainscreen/mercifrenchcafepatisserie/', views.mercifrenchcafepatisserie),
    path('mainscreen/pfchangs/', views.pfchangs),
    path('mainscreen/postinokierland/', views.postinokierland),
    path('mainscreen/simonshotdogs/', views.simonshotdogs),
    path('mainscreen/solmexicancocina/', views.solmexicancocina),
    path('mainscreen/tajmahal/', views.tajmahal),
    path('mainscreen/takedathai/', views.takedathai),
    path('mainscreen/tandooritimes/', views.tandooritimes),
    path('mainscreen/taverngrillescottsdale/', views.taverngrillescottsdale),
    path('mainscreen/thaihouse/', views.thaihouse),
    path('mainscreen/tuttisanti/', views.tuttisanti),
    path('mainscreen/zincbistro/', views.zincbistro),
    path('mainscreen/rated',views.mainrated,name='rated'),
    path('mainscreen/Indian',views.indian,name='indian'),
    path('mainscreen/Chinese',views.china,name='china'),
    path('mainscreen/french',views.french,name='french'),
    path('mainscreen/greece',views.greece,name='greece'),
    path('mainscreen/Indo',views.indo,name='indo'),
    path('mainscreen/Italy',views.italy,name='italy'),
    path('mainscreen/morroco',views.morroco,name='morroco'),
    path('mainscreen/thai',views.thai,name='thai'),
    path('mainscreen/veg',views.veg,name='v'),
    path('mainscreen/nonveg',views.nveg,name='nv'),

    
]